### ISSUE TITLE
Add reason

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot-sidekick#2]
Votes can also have a reason, we should add a reason column to the CSV

**Comment by wa0x6e** [comment]
Already there

https://github.com/snapshot-labs/snapshot-sidekick/pull/1/files#diff-4cc03fae1736909b785e6dfcaa5e6243cc3af11e14d6ae7c698178767c0eb3c8R70

**Comment by samuveth** [comment]
Oh great
