### ISSUE TITLE
refactor: use simple txt file for moderation data

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/snapshot-sidekick#32]
Current moderation data files are using json format, but does not require this structure.

We could simply use text file, with one entry per line, and remove the needs of following json format, with double quotes, comma, etc ...

Also remove errors such as https://github.com/snapshot-labs/snapshot-sidekick/pull/22/files/1744a27635cee9d16cea242d3f94190f5ea75835

**Comment by j0hnfl0w** [comment]
But what about verifiedTokens?

**Comment by wa0x6e** [comment]
we will still support json
