### ISSUE TITLE
feat: Serve lists of flagged proposals and spaces

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot-sidekick#4]
Currently, we are maintaining three lists for flagged proposals and spaces. To improve accessibility and integration, we need to make these lists available on the hub. To achieve this, we should move the lists to Sidekick repo and create an endpoints that serve them.

The existing lists can be found at the following locations:

For proposals (located on the 'Ui' repository):

1. [useProposals.ts#L5](https://github.com/snapshot-labs/snapshot/blob/ad9cb607fb8c33ee4dd86465a9f4361021856486/src/composables/useProposals.ts#L5)
1. [useProposals.ts#L45](https://github.com/snapshot-labs/snapshot/blob/ad9cb607fb8c33ee4dd86465a9f4361021856486/src/composables/useProposals.ts#L45)

For spaces (located in the 'snapshot-spaces' repository), including verified spaces:

1. [verified.json](https://github.com/snapshot-labs/snapshot-spaces/blob/67b67de03d39140e3fb0fd56215a65383006ba63/spaces/verified.json)

**Comment by wa0x6e** [comment]
Do we have a go ahead to implement this feat in this service, instead of the hub ?

**Comment by bonustrack** [comment]
Yes it should be on sidekick

**Comment by samuveth** [comment]
@wa0x6e one thing I forgot to not is that [this](https://github.com/snapshot-labs/snapshot/blob/ad9cb607fb8c33ee4dd86465a9f4361021856486/src/composables/useProposals.ts#L45) list doesn't need to be an object and we can change it to an array
